# Generated by Django 3.2.8 on 2021-11-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main', 'theme__theme'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статей'},
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='main',
            new_name='is_main',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.Scope'),
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
