# Generated by Django 3.2.8 on 2021-11-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211024_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['topic'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статьи'},
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='title',
            new_name='topic',
        ),
        migrations.CreateModel(
            name='ArticleMainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Главный раздел')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('article_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articletag')),
            ],
            options={
                'ordering': ['-is_main'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(through='articles.ArticleMainTag', to='articles.ArticleTag'),
        ),
    ]
