# Generated by Django 3.2.8 on 2021-11-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211102_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tag',
            new_name='article_tags',
        ),
    ]
