# Generated by Django 3.2.8 on 2021-10-30 19:36

from django.db import migrations, models
import measurements.models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=measurements.models.new_file_path),
        ),
    ]
