# Generated by Django 3.2.8 on 2021-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='measurement'),
        ),
    ]
