# Generated by Django 3.2.8 on 2021-10-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Phone1',
        ),
    ]
